// Auto-generated by export_dashboard_data.py — do not edit by hand.
const DASHBOARD_DATA = {
  "generated_at": "2026-07-12T20:23:27.296438+00:00",
  "tickers": [
    "AAPL",
    "ABNB",
    "ADBE",
    "AMZN",
    "CRWD",
    "DIS",
    "META",
    "MSFT",
    "NKE",
    "NVDA",
    "PLTR",
    "TSLA"
  ],
  "sentiment_trend": {
    "AAPL": [
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.0131,
        "n": 8
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.046,
        "n": 47
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.0803,
        "n": 235
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.2019,
        "n": 43
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.0087,
        "n": 17
      }
    ],
    "ABNB": [
      {
        "date": "2026-04-19",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-04-20",
        "avg_sentiment": 0.5978,
        "n": 10
      },
      {
        "date": "2026-04-21",
        "avg_sentiment": 0.475,
        "n": 9
      },
      {
        "date": "2026-04-22",
        "avg_sentiment": 0.8585,
        "n": 4
      },
      {
        "date": "2026-04-23",
        "avg_sentiment": 0.0509,
        "n": 3
      },
      {
        "date": "2026-04-24",
        "avg_sentiment": -0.4645,
        "n": 7
      },
      {
        "date": "2026-04-25",
        "avg_sentiment": 0.669,
        "n": 3
      },
      {
        "date": "2026-04-26",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-04-27",
        "avg_sentiment": 0.4971,
        "n": 2
      },
      {
        "date": "2026-04-28",
        "avg_sentiment": 0.2722,
        "n": 1
      },
      {
        "date": "2026-04-29",
        "avg_sentiment": 0.1771,
        "n": 1
      },
      {
        "date": "2026-04-30",
        "avg_sentiment": -0.1403,
        "n": 4
      },
      {
        "date": "2026-05-01",
        "avg_sentiment": 0.2443,
        "n": 8
      },
      {
        "date": "2026-05-02",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-05-04",
        "avg_sentiment": -0.1919,
        "n": 3
      },
      {
        "date": "2026-05-05",
        "avg_sentiment": -0.3172,
        "n": 2
      },
      {
        "date": "2026-05-06",
        "avg_sentiment": 0.2447,
        "n": 5
      },
      {
        "date": "2026-05-07",
        "avg_sentiment": -0.125,
        "n": 20
      },
      {
        "date": "2026-05-08",
        "avg_sentiment": 0.0516,
        "n": 19
      },
      {
        "date": "2026-05-09",
        "avg_sentiment": 0.0427,
        "n": 2
      },
      {
        "date": "2026-05-11",
        "avg_sentiment": -0.1145,
        "n": 3
      },
      {
        "date": "2026-05-12",
        "avg_sentiment": 0.5,
        "n": 4
      },
      {
        "date": "2026-05-13",
        "avg_sentiment": 0.3097,
        "n": 5
      },
      {
        "date": "2026-05-14",
        "avg_sentiment": 0.5248,
        "n": 2
      },
      {
        "date": "2026-05-18",
        "avg_sentiment": 0.6762,
        "n": 3
      },
      {
        "date": "2026-05-19",
        "avg_sentiment": 0.5647,
        "n": 2
      },
      {
        "date": "2026-05-20",
        "avg_sentiment": 0.6813,
        "n": 5
      },
      {
        "date": "2026-05-21",
        "avg_sentiment": 0.0531,
        "n": 5
      },
      {
        "date": "2026-05-22",
        "avg_sentiment": 0.2723,
        "n": 1
      },
      {
        "date": "2026-05-26",
        "avg_sentiment": 0.8232,
        "n": 2
      },
      {
        "date": "2026-05-27",
        "avg_sentiment": 0.7965,
        "n": 1
      },
      {
        "date": "2026-05-28",
        "avg_sentiment": 0.3601,
        "n": 4
      },
      {
        "date": "2026-05-29",
        "avg_sentiment": -1.0,
        "n": 2
      },
      {
        "date": "2026-06-01",
        "avg_sentiment": 0.3526,
        "n": 3
      },
      {
        "date": "2026-06-02",
        "avg_sentiment": 0.4424,
        "n": 3
      },
      {
        "date": "2026-06-03",
        "avg_sentiment": -0.1172,
        "n": 1
      },
      {
        "date": "2026-06-04",
        "avg_sentiment": 0.2864,
        "n": 3
      },
      {
        "date": "2026-06-05",
        "avg_sentiment": -1.0,
        "n": 2
      },
      {
        "date": "2026-06-06",
        "avg_sentiment": -1.0,
        "n": 1
      },
      {
        "date": "2026-06-07",
        "avg_sentiment": 0.1716,
        "n": 1
      },
      {
        "date": "2026-06-10",
        "avg_sentiment": -0.514,
        "n": 2
      },
      {
        "date": "2026-06-11",
        "avg_sentiment": -0.1339,
        "n": 1
      },
      {
        "date": "2026-06-12",
        "avg_sentiment": -0.629,
        "n": 2
      },
      {
        "date": "2026-06-13",
        "avg_sentiment": 0.4431,
        "n": 1
      },
      {
        "date": "2026-06-15",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-06-16",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-06-17",
        "avg_sentiment": 0.081,
        "n": 3
      },
      {
        "date": "2026-06-18",
        "avg_sentiment": 0.085,
        "n": 3
      },
      {
        "date": "2026-06-19",
        "avg_sentiment": 0.7084,
        "n": 3
      },
      {
        "date": "2026-06-21",
        "avg_sentiment": 0.6811,
        "n": 2
      },
      {
        "date": "2026-06-22",
        "avg_sentiment": -0.1238,
        "n": 3
      },
      {
        "date": "2026-06-23",
        "avg_sentiment": -1.0,
        "n": 1
      },
      {
        "date": "2026-06-24",
        "avg_sentiment": 0.7123,
        "n": 7
      },
      {
        "date": "2026-06-25",
        "avg_sentiment": -0.0832,
        "n": 3
      },
      {
        "date": "2026-06-26",
        "avg_sentiment": 1.0,
        "n": 2
      },
      {
        "date": "2026-06-27",
        "avg_sentiment": 1.0,
        "n": 1
      },
      {
        "date": "2026-06-29",
        "avg_sentiment": 0.8562,
        "n": 7
      },
      {
        "date": "2026-06-30",
        "avg_sentiment": 0.03,
        "n": 8
      },
      {
        "date": "2026-07-02",
        "avg_sentiment": 0.0521,
        "n": 2
      },
      {
        "date": "2026-07-03",
        "avg_sentiment": 1.0,
        "n": 4
      },
      {
        "date": "2026-07-04",
        "avg_sentiment": 1.0,
        "n": 2
      },
      {
        "date": "2026-07-05",
        "avg_sentiment": 0.2189,
        "n": 4
      },
      {
        "date": "2026-07-06",
        "avg_sentiment": 0.0,
        "n": 4
      },
      {
        "date": "2026-07-07",
        "avg_sentiment": 0.6767,
        "n": 6
      },
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.4471,
        "n": 14
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": -0.0612,
        "n": 7
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.4186,
        "n": 2
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.39,
        "n": 1
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.6349,
        "n": 3
      }
    ],
    "ADBE": [
      {
        "date": "2026-07-02",
        "avg_sentiment": 0.2604,
        "n": 23
      },
      {
        "date": "2026-07-03",
        "avg_sentiment": 0.3495,
        "n": 12
      },
      {
        "date": "2026-07-04",
        "avg_sentiment": 0.6754,
        "n": 4
      },
      {
        "date": "2026-07-05",
        "avg_sentiment": 0.5813,
        "n": 7
      },
      {
        "date": "2026-07-06",
        "avg_sentiment": 0.4646,
        "n": 25
      },
      {
        "date": "2026-07-07",
        "avg_sentiment": 0.4096,
        "n": 72
      },
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.4455,
        "n": 50
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": -0.1959,
        "n": 51
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": -0.1431,
        "n": 25
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": -0.7863,
        "n": 8
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": -0.5194,
        "n": 2
      }
    ],
    "AMZN": [
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.4048,
        "n": 26
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.5123,
        "n": 90
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.3506,
        "n": 79
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.53,
        "n": 16
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.5486,
        "n": 6
      }
    ],
    "CRWD": [
      {
        "date": "2026-06-28",
        "avg_sentiment": 1.0,
        "n": 3
      },
      {
        "date": "2026-06-29",
        "avg_sentiment": 0.158,
        "n": 19
      },
      {
        "date": "2026-06-30",
        "avg_sentiment": 0.3277,
        "n": 14
      },
      {
        "date": "2026-07-01",
        "avg_sentiment": 0.32,
        "n": 21
      },
      {
        "date": "2026-07-02",
        "avg_sentiment": 0.1876,
        "n": 30
      },
      {
        "date": "2026-07-03",
        "avg_sentiment": -0.1041,
        "n": 2
      },
      {
        "date": "2026-07-05",
        "avg_sentiment": 0.1821,
        "n": 6
      },
      {
        "date": "2026-07-06",
        "avg_sentiment": 0.2864,
        "n": 38
      },
      {
        "date": "2026-07-07",
        "avg_sentiment": 0.5607,
        "n": 16
      },
      {
        "date": "2026-07-08",
        "avg_sentiment": -0.052,
        "n": 24
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.3149,
        "n": 16
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.1524,
        "n": 34
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": -0.6632,
        "n": 17
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": -0.5292,
        "n": 2
      }
    ],
    "DIS": [
      {
        "date": "2026-07-01",
        "avg_sentiment": 0.0082,
        "n": 60
      },
      {
        "date": "2026-07-02",
        "avg_sentiment": 0.2405,
        "n": 50
      },
      {
        "date": "2026-07-04",
        "avg_sentiment": 0.1076,
        "n": 6
      },
      {
        "date": "2026-07-05",
        "avg_sentiment": 0.3693,
        "n": 4
      },
      {
        "date": "2026-07-06",
        "avg_sentiment": 0.0703,
        "n": 20
      },
      {
        "date": "2026-07-07",
        "avg_sentiment": 0.0784,
        "n": 28
      },
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.2823,
        "n": 36
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.3321,
        "n": 35
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.3753,
        "n": 30
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.0408,
        "n": 7
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.2797,
        "n": 5
      }
    ],
    "META": [
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.7344,
        "n": 1
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": -0.0009,
        "n": 27
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.2277,
        "n": 215
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.3237,
        "n": 70
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": -0.0193,
        "n": 26
      }
    ],
    "MSFT": [
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.1224,
        "n": 5
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.3017,
        "n": 41
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": -0.0285,
        "n": 241
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": -0.1662,
        "n": 41
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": -0.1501,
        "n": 36
      }
    ],
    "NKE": [
      {
        "date": "2026-07-07",
        "avg_sentiment": -0.0047,
        "n": 23
      },
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.3113,
        "n": 104
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.082,
        "n": 73
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.552,
        "n": 92
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.4969,
        "n": 21
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.5028,
        "n": 14
      }
    ],
    "NVDA": [
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.3777,
        "n": 59
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.4419,
        "n": 159
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.3222,
        "n": 115
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.2948,
        "n": 36
      }
    ],
    "PLTR": [
      {
        "date": "2026-07-08",
        "avg_sentiment": 0.6088,
        "n": 15
      },
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.1805,
        "n": 41
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.2858,
        "n": 266
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.2351,
        "n": 34
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.4675,
        "n": 17
      }
    ],
    "TSLA": [
      {
        "date": "2026-07-09",
        "avg_sentiment": 0.3939,
        "n": 51
      },
      {
        "date": "2026-07-10",
        "avg_sentiment": 0.1048,
        "n": 232
      },
      {
        "date": "2026-07-11",
        "avg_sentiment": 0.0695,
        "n": 52
      },
      {
        "date": "2026-07-12",
        "avg_sentiment": 0.4612,
        "n": 15
      }
    ]
  },
  "daily_volume": [
    {
      "date": "2026-07-09",
      "count": 769
    },
    {
      "date": "2026-07-10",
      "count": 811
    },
    {
      "date": "2026-07-11",
      "count": 3124
    },
    {
      "date": "2026-07-12",
      "count": 380
    }
  ]
};
