"""
export_dashboard_data.py — Reads pipeline.db and writes dashboard/data.js,
a plain JS file (`const DASHBOARD_DATA = {...};`) that dashboard.html loads
via a normal <script> tag.

Written as a .js assignment rather than a .json file on purpose: opening
dashboard.html directly from disk (file://) triggers CORS restrictions on
fetch() in most browsers, but a same-folder <script src="data.js"> tag
loads fine with no local server needed.

Two datasets:

  1. sentiment_trend — per ticker, per calendar day (by message timestamp,
     not date_collected), the average sentiment_score. Scoped to
     source='stocktwits' and relevance_flag excluded, matching exactly what
     build_confidence_trajectory.py treats as evidence — so the chart shows
     what's actually driving signals, not a superset of raw scraped noise.

  2. daily_volume — total StockTwits row count per calendar day, grouped by
     date_collected (when the scraper actually pulled it in), summed across
     every scrape run that day. This is scraping activity, not message
     publish date — a busy scrape day shows as a tall bar regardless of how
     old the messages it caught up on were.

Read-only. Safe to re-run anytime; each run fully overwrites data.js with
a fresh snapshot as of that moment. Not wired into run_pipeline.py —
re-run manually (or archive/schedule separately) whenever you want the
dashboard to reflect the latest data.
"""
import json
import sqlite3
from pathlib import Path
from datetime import datetime, timezone

DB_PATH = Path(__file__).parent.parent / "data" / "pipeline.db"
OUTPUT_PATH = Path(__file__).parent / "data.js"


def get_active_tickers(conn):
    cur = conn.cursor()
    cur.execute("SELECT ticker FROM companies WHERE active = 1 ORDER BY ticker")
    return [row[0] for row in cur.fetchall()]


def get_sentiment_trend(conn):
    cur = conn.cursor()
    cur.execute(
        """
        SELECT ticker, date(timestamp) AS day, AVG(sentiment_score), COUNT(*)
        FROM sentiment_records
        WHERE source = 'stocktwits'
          AND sentiment_score IS NOT NULL
          AND (relevance_flag IS NULL OR relevance_flag = 0)
        GROUP BY ticker, day
        ORDER BY ticker, day
        """
    )
    by_ticker = {}
    for ticker, day, avg_score, n in cur.fetchall():
        by_ticker.setdefault(ticker, []).append(
            {"date": day, "avg_sentiment": round(avg_score, 4), "n": n}
        )
    return by_ticker


def get_daily_volume(conn):
    cur = conn.cursor()
    cur.execute(
        """
        SELECT date(date_collected) AS day, COUNT(*)
        FROM sentiment_records
        WHERE source = 'stocktwits'
        GROUP BY day
        ORDER BY day
        """
    )
    return [{"date": day, "count": count} for day, count in cur.fetchall()]


def run():
    if not DB_PATH.exists():
        raise FileNotFoundError(f"No database found at {DB_PATH.resolve()} — check the path.")

    conn = sqlite3.connect(DB_PATH)

    tickers = get_active_tickers(conn)
    sentiment_trend = get_sentiment_trend(conn)
    daily_volume = get_daily_volume(conn)

    conn.close()

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "tickers": tickers,
        "sentiment_trend": sentiment_trend,
        "daily_volume": daily_volume,
    }

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by export_dashboard_data.py — do not edit by hand.\n")
        f.write("const DASHBOARD_DATA = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")

    total_trend_points = sum(len(v) for v in sentiment_trend.values())
    print(f"Wrote {OUTPUT_PATH}")
    print(f"  {len(tickers)} tickers")
    print(f"  {total_trend_points} sentiment_trend points across all tickers")
    print(f"  {len(daily_volume)} days of activity volume data")


if __name__ == "__main__":
    run()
